#
#  makefile.osf1 - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2024 - macmpi, MT
#
#  generic makefile for Tru64 UNIX.
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note seperator (tab) at the beginning of the line CANNOT be a space..!
#
#  26 Nov 23         - Initial version - MT
#                    - Define OSF1 so conditional compilation works even if
#                      the compiler doesn't define it automatically - MT
#                    - Tidied up comments - MT
#  25 Feb 24         - Added font module - MT
#  02 Mar 24         - Fixed missing target - MT
#  20 Mar 24         - Updated change history - MT
#                    - Fixed issue with directory creation - MT
#                    - Renamed $TARGET to $BIN - MT
#  24 Mar 24         - Updated to use $SHARED and $COMMON source files - MT
#                    - Added 'make all' and 'make clean' - MT
#                    - Split compilation of the common and shared code into
#                      seperate tasks (which is up to be 18% quicker) - MT
#  27 Mar 24         - Aligned rules with the generic makefile - MT
#  31 Mar 24         - Leverage src/makefile.common
#  18 Aug 25         - Define __osf__ (as the compiler doesn't) - MT
#

LANG	=  LANG_en
CFLAGS	= -D__osf__
LDFLAGS	=
LDLIBS	=

include makefile.all
