#
#  makefile - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2019 - MT
#
#  makefile.darwin
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note seperator (tab) at the beginning of the line CANNOT be a space..!
#
#  https://stackoverflow.com/questions/50941196/
#
#  https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
#
#  12 May 24         - Initial version - MT
#   5 Sep 25         - Builds with GTK 3.0 to provide support for graphical
#                      file selection dialog - MT
# 15 Sep  25         - Detects of GTK 3.0 is available - MT
#

CFLAGS	+= -I/opt/X11/include/
LDFLAGS += -L/opt/X11/lib/
LDLIBS	?=

LANG 	= LANG_en

ifneq ($(shell pkg-config --exists gtk+-3.0 && echo "GTK" || echo ""),)
CFLAGS	+= -D__GTK__
CFLAGS	+= `pkg-config --cflags gtk+-3.0`
LDLIBS	+= `pkg-config --libs gtk+-3.0`
endif
ifneq ($(COMMIT),)
CFLAGS	+= -DCOMMIT_ID='"[Commit Id : $(COMMIT)]"'
endif
ifneq ($(SCALE_WIDTH),)
CFLAGS	+= -DSCALE_WIDTH=$(SCALE_WIDTH)
endif
ifneq ($(SCALE_HEIGHT),)
CFLAGS	+= -DSCALE_HEIGHT=$(SCALE_HEIGHT)
endif

include makefile.all
