#
#  makefile.all_flavors - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2024 - macmpi, MT
#
#  generic makefile for linux/NetBSD/Darwin
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note seperator (tab) at the beginning of the line CANNOT be a space..!
#
#  https://stackoverflow.com/questions/50941196/
#
#  https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
#
#  28 Mar 24         - Initial version - macmpi
#  28 Mar 24         - Streamlined macros for use on osf1 - macmpi
#  09 Apr 24         - Finally renamed x11-calc-segment to the more correct
#                      x11-calc-digit - MT
#  29 Apr 24         - Renamed makefile.all_flavors - macmpi
#                    - Renamed makefile.all - MT
#  31 Jul 25         - Display file names in colour (if possible) - MT
#  11 Aug 25         - Do not use -Wno-builtin-macro-redefined - MT
#  18 Aug 25         - Attempt to define compiler - MT
#  20 Sep 25         - Fixed issue with compiler version - MT
#  01 Nov 25         - Added a x11-calc-card - MT
#  14 Nov 25         - Added x11-calc-register - MT
#                    - Disable optimization when debugging - MT
#  22 Nov 25         - Strip newline from COMPILER string - MT
#

MODEL		= 21
PROGRAM		= x11-calc-$(MODEL)
BIN		= ../bin

COMPILER	= `$(CC) -v 2>&1 | grep ' version ' | sed -e 's/([^()]*)//g' | sed -e 's/[ \t]*$$//g' | awk '{printf "%s",$$0}'`  # Strip newline

# Note   SHARED sources are model dependant and are recompiled for every emulator
#        COMMON code is only compiled once an cannot contain model dependent code blocks

SHARED		= x11-calc.c x11-calc-cpu.c x11-calc-display.c x11-calc-digit.c x11-calc-messages.c x11-calc-button.c x11-calc-card.c
COMMON		=  x11-calc-register.c x11-calc-switch.c x11-calc-label.c x11-calc-colour.c x11-calc-font.c x11-keyboard.c gcc-wait.c gcc-exists.c

CC		= cc
#DEBUG		= -O0 -g
DEBUG		=

LDLIBS_ADD	= -lX11 -lm

CFLAGS_ADD	= -D$(LANG) -D__compiler__="\"$(COMPILER)\"" $(DEBUG) -fcommon -Wall -pedantic -std=gnu99 \
			-Wno-comment -Wno-deprecated-declarations # -Wno-builtin-macro-redefined

all: $(BIN)/$(PROGRAM)

$(BIN)/$(PROGRAM): common $(SHARED:.c=.o_HP$(MODEL)) x11-calc-$(MODEL).o
	@mkdir -p $(BIN)
	@rm -f $(BIN)/$(PROGRAM)
	@[ -n "$${VERBOSE+x}" ] && echo && \
		echo "$(CC) $(SHARED:.c=.o_HP$(MODEL)) $(COMMON:.c=.o_cm) x11-calc-$(MODEL).o $(LDFLAGS) $(LDLIBS) $(LDLIBS_ADD) -o $@" \
		|| true
	@$(CC) $(SHARED:.c=.o_HP$(MODEL)) $(COMMON:.c=.o_cm) x11-calc-$(MODEL).o $(LDFLAGS) $(LDLIBS) $(LDLIBS_ADD) -o $@
	@if ls --color $@ > /dev/null 2>&1 ;then  ls --color $@ | sed "s:$(BIN)/::g"; else ls $@ | sed "s:$(BIN)/::g"; fi
#	@ls $@ | sed "s:$(BIN)/::g"

common: $(COMMON:.c=.o_cm)

.SUFFIXES: .o_cm .o_HP$(MODEL) .o

.c.o_HP$(MODEL):
	@[ -n "$${VERBOSE+x}" ] && echo && echo "$(CC) $(CFLAGS) $(CFLAGS_ADD) -DHP$(MODEL) -c $< -o $@" || true
	@$(CC) $(CFLAGS) $(CFLAGS_ADD) -DHP$(MODEL) -c $< -o $@

.c.o:
	@[ -n "$${VERBOSE+x}" ] && echo && echo "$(CC) $(CFLAGS) $(CFLAGS_ADD) -DHP$(MODEL) -c $< -o $@" || true
	@$(CC) $(CFLAGS) $(CFLAGS_ADD) -DHP$(MODEL) -c $< -o $@

# COMMON files are NOT supposed to be instantiated per MODEL
.c.o_cm:
	@[ -n "$${VERBOSE+x}" ] && echo && echo "$(CC) $(CFLAGS) $(CFLAGS_ADD) -c $< -o $@" || true
	@$(CC) $(CFLAGS) $(CFLAGS_ADD) -c $< -o $@

clean:
	@rm -f $(SHARED:.c=.o_HP$(MODEL)) $(COMMON:.c=.o_cm) x11-calc-$(MODEL).o
