#
#  makefile - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2025 - MT
#
#  makefile for Minix 3.4
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note seperator (tab) at the beginning of the line CANNOT be a space..!
#
#  12 Oct 25         - Initial version - MT
#

CFLAGS	?=
LDFLAGS	?=
LDLIBS	?=

OS	!= uname -s

LANG	= LANG_en
CFLAGS	+= -Wno-variadic-macros
CFLAGS	+= -I/usr/X11R7/include/
LDFLAGS	+= -L/usr/X11R7/lib/

CC	= clang

include makefile.all
